{
    "extends": ["eslint:recommended", "prettier"],
    "plugins": ["prettier"],
    "rules":
        {
            "prettier/prettier": ["error"],
            "indent": ["error", 4],
            "require-jsdoc": 0
        },
    "parserOptions": { "ecmaVersion": 2018 },
    "env": { "es6": true, "node": true}
}
